# Generated by Django 3.2.2 on 2021-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210506_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Black', 'Black'), ('Blue', 'Blue'), ('Green', 'Green'), ('Grey', 'Grey')], default='White', max_length=6),
        ),
    ]
