# Generated by Django 3.2.2 on 2021-05-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210506_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='present',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
