# Generated by Django 3.2.2 on 2021-05-06 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_car_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 10, 20, 53, 16740)),
        ),
    ]
