# Generated by Django 3.2.2 on 2021-05-06 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_deal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
