# Generated by Django 3.2.2 on 2021-05-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_deal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='realprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
